apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipment-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: equipment-service
    spec:
      containers:
        - name: equipment-service
          image: outoftheparkacr.azurecr.io/equipment-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: equipment-service-deployment
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: equipment-service
  type: ClusterIP
